### ISSUE TITLE
After auth, redirects back to the *.herokuapp.com URL, not the www.ft.com URL

### ISSUE THREAD

**Issue by callumlocke** [Financial-Times/s3o-middleware#40]
If I visit https://www.ft.com/ge2017/results (which is really a vanity for something in the service registry at https://www.ft.com/election-results/ge2017), it is redirected by s3o middleware (which I enabled to prevent public access to the page before it is intended to go live) to Google login. But after authentication, the browser is redirected back to the original Heroku app (https://ft-ig-general-election-2017-eu.herokuapp.com/election-results/ge2017).

What is the best way to fix this? Is there some way to tell Heroku what the canonical public URL is? Or do I just have to configure s3o-middleware to override the redirect URL?

**Comment by lucas42** [comment]
I think the problem here is that fastly is rewriting the host header, so heroku (and hence s3o-middleware) has no way of working out what the correct host should be.
Normally, I'd suggest passing the original host header through the CDN and configuring heroku to accept that.  However, I'm guessing the ft.com CDN config routes to lots of different heroku apps, so I'm not sure if that'd even work in this case.

**Comment by callumlocke** [comment]
Aren't there lots of FT apps on Heroku that have solved this problem already?

**Comment by lucas42** [comment]
No, we don't usually put s3o on user-facing sites.  And generally staff-facing sites have a one-to-one relationship between hostname and heroku app, so it's fine for heroku to be configured with that hostname.

Have you though about hiding it behind a feature flag instead of s3o?  I think this is what next generally do for parts of the site not ready for public consumption.

**Comment by callumlocke** [comment]
OK I see, thanks. I'll look into using a flag instead.
